---
abstract: unknown
author:
  - 'Pef Secure'
build_requires:
  ExtUtils::MakeMaker: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.1, CPAN::Meta::Converter version 2.143240'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DBIx-Struct
no_index:
  directory:
    - t
    - inc
requires:
  DBIx::Connector: '0.52'
  Digest::MD5: '0'
  SQL::Abstract: '0'
  perl: '5.14'
resources:
  bugtracker: https://github.com/pef-secure/dbix-struct/issues
  repository: https://github.com/pef-secure/dbix-struct.git
version: '0.05'
